version: '3'

services:
  redis:
    image: redis:alpine
    container_name: tx-benchmark-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle:0.14.2
    container_name: tx-benchmark-tigerbeetle
    ports:
      - "3000:3000"
    command: start --addresses=0.0.0.0:3000 --cluster-id=0 --memory=true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 5s
      timeout: 5s
      retries: 3
